### ISSUE TITLE
Ignore " : " in .zsh_history

### ISSUE THREAD

**Issue by shvedes** [nate-sys/muc#10]
add option to ignore this character
![image](https://user-images.githubusercontent.com/84767665/209653134-a5254597-02a9-48ef-8539-41c9cfb82c70.png)

**Comment by nthnd** [comment]
> add option to ignore this character
> ![image](https://user-images.githubusercontent.com/84767665/209653134-a5254597-02a9-48ef-8539-41c9cfb82c70.png)
> 

Easy fix, I'll get on it as soon as possible.
I'm kind of curious on how it's so prominent in your history tho

**Comment by shvedes** [comment]
I just reinstalled my arch, and now muc show zero instead " : "
![image](https://user-images.githubusercontent.com/84767665/209962389-a2416128-9aae-43d3-8649-51c429ee8711.png)

**Comment by nthnd** [comment]
> I just reinstalled my arch, and now muc show zero instead " : " 
have you tried setting --shell zsh?

**Comment by shvedes** [comment]
Oh, its working, thanks! Ii didn't know about this update
