### ISSUE TITLE
Cargo compile fails: error[E0658]: `let...else` statements are unstable

### ISSUE THREAD

**Issue by anemovva** [nate-sys/muc#15]
When I try to compile the project with `cargo build --release`, the compile fails with the following error:
error[E0658]: `let...else` statements are unstable.

The full error is:
error[E0658]: `let...else` statements are unstable
  --> src/hist_file.rs:16:5
   |
16 |     let Ok(histfile_buffer) = std::fs::File::open(&args.file) else { panic!("Please specify a valid histfile")};
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information
   = help: add `#![feature(let_else)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `muc` due to previous error                                                                                     /0.3s

I am using rustup version 1.25.1-2.

**Comment by nthnd** [comment]
I started coding this in rust 1.6.5. iirc that was when `let ... else` became stable. Compile it in a later version for it to work.
