### ISSUE TITLE
`thread 'main' panicked at 'HISTFILE not set: NotPresent', src/main.rs:13:42`

### ISSUE THREAD

**Issue by kresimirko** [nate-sys/muc#30]
Runs when trying to run `muc`, with and without arguments.

Installed through `cargo install --git=https://github.com/nate-sys/muc` as instructed in the Readme. `rustc` version is `1.68.0`.

Short backtrace:
```
thread 'main' panicked at 'HISTFILE not set: NotPresent', src/main.rs:13:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   3: muc::main
```

**Comment by nthnd** [comment]
Is you'r histfile environment variable set?

Try running it with `HISTFILE=/path/to/histfile muc`

**Comment by kresimirko** [comment]
Yes, it is set.

![image](https://user-images.githubusercontent.com/104278083/225592825-c15a2bd7-ce71-4d21-898f-73422e827489.png)

**Comment by nthnd** [comment]
The problem arises because `std::env::var()` is not finding that environment variable for some reason.
Can you manually add the `HISTFILE` in your zshrc and try again after restarting the shell?

**Comment by nthnd** [comment]
Not sure how to fix this, but for now the `--file` option is back

**Comment by nthnd** [comment]
Ah, `$HISTFILE` doesn't get exported even thought it may be set. That's an overlook by me. 
Now, you either have to pass the file-path yourself or export HISTFILE. whichever works for you.
