### ISSUE TITLE
zsh_history issues

### ISSUE THREAD

**Issue by ghost** [nate-sys/muc#32]
Running on zsh_history (OhMyZSH) results in this error
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/hist_file.rs:89:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This can be fixed by replacing:
https://github.com/nate-sys/muc/blob/d8336bc2f387c79b33c87cf2aba28d3c93486af2/src/hist_file.rs#L87-L89
with: 
```rs
        let words = line.split_whitespace().collect::<Vec<&str>>();
        if words.first().is_none() {
            continue;
        }

        let (first, second) = (words.first().unwrap().to_string(), words.get(1));
```
the last value of `words` is None, unwrapping it causes an error.

after the fix there is another issue:
```
 [▮▮▮▮▮▮▮▮▮▮] 54.01%  9826 :  -- No idea what this is supposed to mean.
[▮         ]  7.51%  1367 ls 
[▮         ]  6.97%  1268 cd 
[          ]  4.82%   877 vi 
[          ]  2.35%   428 yay 
[          ]  2.19%   399 sudo -e, rm, mount ... -- intentional?
[          ]  1.74%   317 rm 
[          ]  1.72%   313 killall 
[          ]  1.43%   261 cargo 
[          ]  1.34%   243 curl 
...2894 (15.91%) others
```

**Comment by nthnd** [comment]
This is an issue with how the ohmyzsh histfile works. There was a similar issue with fish histfiles. There is some nuance with how these systems store history which I haven't fully looked at yet. 

If you can, can you submit any resources on how an ohmyzsh histfile looks like?

**Comment by ghost** [comment]
Sure!
**Time stamps wont match. These are snippets from different parts of the file (privacy reasons)** 
```
: 1681642385:0;ls
: 1681642386:0;cd
: 1681642386:0;ls

: 1681590299:0;cd ..
: 1681590300:0;ls
: 1681603417:0;cd
: 1681603417:0;ls

: 1681588614:0;cd
: 1681588615:0;ls
: 1681588616:0;cd [REDACTED]
: 1681588617:0;ls
: 1681588618:0;gb
: 1681588620:0;g log
: 1681588624:0;g checkout main
```

**Comment by nthnd** [comment]
Can you try building from the ohmyzsh branch? I've written something that works with the sample you provided. Want to make sure that there are no irregularities

**Comment by ghost** [comment]
> Can you try building from the ohmyzsh branch? I've written something that works with the sample you provided. Want to make sure that there are no irregularities

Sorry for late response.
I no longer use OMZ.
I will close with the assumption that it was fixed.

Thank you.
