### ISSUE TITLE
Ignore `sudo` / `doas`

### ISSUE THREAD

**Issue by xezo360hye** [nate-sys/muc#6]
I am not sure if this is why `--prefix` exists but I could not make it work myself. There are many commands I start with `sudo` and Muc only shows `sudo` at the top. IMHO it should look into the actual command somehow (at least just use the next word), maybe make a flag to toggle (or if possible instructions on how to achieve this with `--prefix` or whatever other flags)

**Comment by nthnd** [comment]
Working on that too.

I'm thinking of adding a feature that lets you specify subcommands. This would add more information for things like git, sudo, entr ... etc

**Comment by jitmussi** [comment]
> I'm thinking of adding a feature that lets you specify subcommands. This would add more information for things like git, sudo, entr ... etc

In that vein, there should be at least some distinction between a "sub command" such as, "git commit" vs a "leader" command like "sudo apt".

**Comment by nthnd** [comment]
48b750ee4c795b38d3e0a7a75a644b5b25a081ac
